version: '3.8'
services:
  wallet:
    container_name: 'eden-spending-wallet'
    build: ./wallet
    ports:
      - '8888:8888'
    volumes:
      - ./tmp/wallet/:/opt/application/data/
  postgres:
    container_name: 'eden-spending-postgres'
    image: postgres:12.12-bullseye
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
  hapi:
    container_name: 'eden-spending-hapi'
    image: node:16.17.0-slim
    ports:
      - '9090:9090'
    volumes:
      - ./tmp/hapi/node_modules/:/app/node_modules/
      - type: bind
        source: ./hapi
        target: /app
    working_dir: /app
    command: bash -c "yarn && yarn watch"
    environment:
      HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
      HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
      HAPI_NETWORK_API: '${HAPI_NETWORK_API}'
      HAPI_NETWORK_CHAIN_ID: '${HAPI_NETWORK_CHAIN_ID}'
      HAPI_NETWORK_BASE_ACCOUNT: '${HAPI_NETWORK_BASE_ACCOUNT}'
      HAPI_NETWORK_BASE_PASSWORD: '${HAPI_NETWORK_BASE_PASSWORD}'
      HAPI_NETWORK_WALLET_URL: '${HAPI_NETWORK_WALLET_URL}'
      HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
      HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
      HAPI_RATE_HISTORY: '${HAPI_RATE_HISTORY}'
      HAPI_EDEN_ELECTION_INTERVAL: '${HAPI_EDEN_ELECTION_INTERVAL}'
      HAPI_EDEN_HISTORIC_ELECTION: '${HAPI_EDEN_HISTORIC_ELECTION}'
      HAPI_EDEN_CONTRACT: '${HAPI_EDEN_CONTRACT}'
      HAPI_DFUSE_API_KEY: '${HAPI_DFUSE_API_KEY}'
      HAPI_DFUSE_API: '${HAPI_DFUSE_API}'
      HAPI_DFUSE_FIRST_BLOCK: '${HAPI_DFUSE_FIRST_BLOCK}'
  hasura:
    container_name: 'eden-spending-hasura'
    image: hasura/graphql-engine:v2.10.1.cli-migrations-v3
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    volumes:
      - ./hasura/migrations:/migrations
      - ./hasura/metadata:/metadata
      - ./hasura/seeds:/seeds
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_METADATA_DIR: /metadata
      HASURA_GRAPHQL_SEEDS_DIR: /seeds
      HASURA_GRAPHQL_ACTION_BASE_URL: '${HASURA_GRAPHQL_ACTION_BASE_URL}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      # Local Development Configurations It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_LOGGING: 'true'
      # disabled security for local development
      # HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      # HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
  webapp:
    container_name: 'eden-spending-webapp'
    image: node:16.17.0
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./tmp/webapp/node_modules/:/app/node_modules/
      - type: bind
        source: ./webapp
        target: /app
    working_dir: /app
    command: bash -c "yarn && yarn start"
    environment:
      REACT_APP_TAG: '${REACT_APP_TAG}'
      REACT_APP_TITLE: '${REACT_APP_TITLE}'
      REACT_APP_LOGO: '${REACT_APP_LOGO}'
      REACT_APP_FOOTER_LINKS: '${REACT_APP_FOOTER_LINKS}'
      REACT_APP_UAL_APP_NAME: '${REACT_APP_UAL_APP_NAME}'
      REACT_APP_UAL_API_PROTOCOL: '${REACT_APP_UAL_API_PROTOCOL}'
      REACT_APP_UAL_API_HOST: '${REACT_APP_UAL_API_HOST}'
      REACT_APP_UAL_API_PORT: '${REACT_APP_UAL_API_PORT}'
      REACT_APP_UAL_CHAIN_ID: '${REACT_APP_UAL_CHAIN_ID}'
      REACT_APP_HASURA_URL: '${REACT_APP_HASURA_URL}'
      REACT_APP_RATE_HISTORY: '${REACT_APP_RATE_HISTORY}'
      REACT_APP_EDEN_CONTRACT: '${REACT_APP_EDEN_CONTRACT}'
volumes:
  postgres_data:
