-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."total_expense_by_delegate_and_election" add column "account" varchar
--  null;
