apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  # webapp
  PORT: '${PORT}'
  REACT_APP_TTILE: '${REACT_APP_TTILE}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  # postgres
  POSTGRES_USER: '${POSTGRES_USER}'
  POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  POSTGRES_DB: '${POSTGRES_DB}'
  POSTGRES_DATA: '${POSTGRES_DATA}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-config
data:
  # hapi
  HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
  HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
  HAPI_NETWORK_API: '${HAPI_NETWORK_API}'
  HAPI_NETWORK_CHAIN_ID: '${HAPI_NETWORK_CHAIN_ID}'
  HAPI_NETWORK_BASE_ACCOUNT: '${HAPI_NETWORK_BASE_ACCOUNT}'
  HAPI_NETWORK_BASE_PASSWORD: '${HAPI_NETWORK_BASE_PASSWORD}'
  HAPI_NETWORK_WALLET_URL: '${HAPI_NETWORK_WALLET_URL}'
  HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
  HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
  HAPI_RATE_HISTORY: '${HAPI_RATE_HISTORY}'
  HAPI_EDEN_ELECTION_INTERVAL: '${HAPI_EDEN_ELECTION_INTERVAL}'
  HAPI_EDEN_HISTORIC_ELECTION: '${HAPI_EDEN_HISTORIC_ELECTION}'
  HAPI_EDEN_CONTRACT: '${HAPI_EDEN_CONTRACT}'
  HAPI_DFUSE_API_KEY: '${HAPI_DFUSE_API_KEY}'
  HAPI_DFUSE_API: '${HAPI_DFUSE_API}'
  HAPI_DFUSE_FIRST_BLOCK: '${HAPI_DFUSE_FIRST_BLOCK}'
  HAPI_DFUSE_FIRST_TREASURY_BLOCK: '${HAPI_DFUSE_FIRST_TREASURY_BLOCK}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
data:
  # hasura
  HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
  HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
  HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
  HASURA_GRAPHQL_ACTION_BASE_URL: '${HASURA_GRAPHQL_ACTION_BASE_URL}'
