-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."eden_delegates" add column "last_synced_at" int8
--  not null default '209274902';
