name: Build images from latest master branch

on:
  push:
    tags:
      - v*

jobs:
  create-prod-image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          # webapp
          PORT: 80
          REACT_APP_TAG: ${{ github.ref }}
          REACT_APP_VERSION: ${{ github.ref }}
          REACT_APP_NAME: 'eden-spending'
          REACT_APP_TITLE: 'Eden on EOS Accounting Standard'
          REACT_APP_LOGO: 'https://raw.githubusercontent.com/eoscostarica/design-assets/master/logos/eosCR/fullColor-vertiall-transparent-white.png'
          REACT_APP_FOOTER_LINKS: '[]'
          REACT_APP_UAL_APP_NAME: 'EOS Reports'
          REACT_APP_UAL_API_PROTOCOL: 'https'
          REACT_APP_UAL_API_HOST: 'eos.greymass.com'
          REACT_APP_UAL_API_PORT: '443'
          REACT_APP_UAL_CHAIN_ID: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906'
          REACT_APP_HASURA_URL: ${{ secrets.REACT_APP_HASURA_URL }}
          REACT_APP_RATE_HISTORY: ${{ secrets.REACT_APP_RATE_HISTORY }}
          REACT_APP_EDEN_CONTRACT: 'genesis.eden'

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          # general
          NAMESPACE: eden-spending
          INGRESS_HOST: spending.eden.eoscommunity.org
          INGRESS_GRAPHQL_HOST: graphql-spending.eden.eoscommunity.org
          # Postgres
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_DATA: ${{ secrets.POSTGRES_DATA }}
          # hapi
          HAPI_SERVER_PORT: 9090
          HAPI_SERVER_ADDRESS: 0.0.0.0
          HAPI_NETWORK_API: 'https://eos.edenia.cloud'
          HAPI_NETWORK_CHAIN_ID: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906'
          HAPI_NETWORK_BASE_ACCOUNT: ${{ secrets.HAPI_NETWORK_BASE_ACCOUNT }}
          HAPI_NETWORK_BASE_PASSWORD: ${{ secrets.HAPI_NETWORK_BASE_PASSWORD }}
          HAPI_NETWORK_WALLET_URL: ${{ secrets.HAPI_NETWORK_WALLET }}
          HAPI_HASURA_URL: ${{ secrets.HAPI_HASURA_URL }}
          HAPI_HASURA_ADMIN_SECRET: ${{ secrets.HAPI_HASURA_ADMIN_SECRET }}
          HAPI_RATE_HISTORY: ${{secrets.HAPI_RATE_HISTORY }}
          HAPI_EDEN_ELECTION_INTERVAL: 7889400
          HAPI_EDEN_HISTORIC_ELECTION: ${{secrets.HAPI_EDEN_HISTORIC_ELECTION}}
          HAPI_EDEN_CONTRACT: genesis.eden
          HAPI_DFUSE_API_KEY: ${{secrets.HAPI_DFUSE_API_KEY}}
          HAPI_DFUSE_API: eos.dfuse.eosnation.io
          HAPI_DFUSE_FIRST_BLOCK: ${{secrets.HAPI_DFUSE_FIRST_BLOCK}}
          # hasura
          HASURA_GRAPHQL_ENABLE_CONSOLE: true
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${{ secrets.HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}
          HASURA_GRAPHQL_ACTION_BASE_URL: ${{ secrets.HASURA_GRAPHQL_ACTION_BASE_URL }}

      - name: Deploy kubernetes files
        uses: steebchen/kubectl@v1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: eden-spending
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
