name: Build images from latest dev branch

on:
  push:
    branches:
      - dev

jobs:
  create-dev-image:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          IMAGE_NAME_WEBAPP: eden-spending-webapp-dev
          IMAGE_NAME_HAPI: eden-spending-hapi-dev
          IMAGE_NAME_HASURA: eden-spending-hasura-dev
          IMAGE_NAME_WALLET: eden-spending-wallet-dev
          # webapp
          PORT: 80
          REACT_APP_TAG: ${{ github.ref }}
          REACT_APP_NAME: 'eden-spending'
          REACT_APP_TITLE: 'Eden on EOS Accounting Standard'
          REACT_APP_LOGO: 'https://raw.githubusercontent.com/eoscostarica/design-assets/master/logos/eosCR/fullColor-vertiall-transparent-white.png'
          REACT_APP_FOOTER_LINKS: '[]'
          REACT_APP_UAL_APP_NAME: 'EOS Reports'
          REACT_APP_UAL_API_PROTOCOL: 'https'
          REACT_APP_UAL_API_HOST: 'jungle4.api.eosnation.io'
          REACT_APP_UAL_API_PORT: '443'
          REACT_APP_UAL_CHAIN_ID: '73e4385a2708e6d7048834fbc1079f2fabb17b3c125b146af438971e90716c4d'
          REACT_APP_HASURA_URL: ${{ secrets.DEV_REACT_APP_HASURA_URL }}
          REACT_APP_RATE_HISTORY: ${{ secrets.DEV_REACT_APP_RATE_HISTORY }}
          REACT_APP_EDEN_CONTRACT: 'genesis.eden'

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          # general
          NAMESPACE: eden-spending
          INGRESS_HOST: spending.eden.edenia.cloud
          INGRESS_GRAPHQL_HOST: spending-graphql.eden.edenia.cloud
          IMAGE_NAME_WEBAPP: eden-spending-webapp-dev
          IMAGE_NAME_HAPI: eden-spending-hapi-dev
          IMAGE_NAME_HASURA: eden-spending-hasura-dev
          IMAGE_NAME_WALLET: eden-spending-wallet-dev
          # Postgres
          POSTGRES_USER: ${{ secrets.DEV_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DEV_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DEV_POSTGRES_DB }}
          POSTGRES_DATA: ${{ secrets.DEV_POSTGRES_DATA }}
          # hapi
          HAPI_SERVER_PORT: 9090
          HAPI_SERVER_ADDRESS: 0.0.0.0
          HAPI_NETWORK_API: 'https://jungle4.api.eosnation.io'
          HAPI_NETWORK_CHAIN_ID: '73e4385a2708e6d7048834fbc1079f2fabb17b3c125b146af438971e90716c4d'
          HAPI_NETWORK_BASE_ACCOUNT: ${{ secrets.DEV_HAPI_NETWORK_BASE_ACCOUNT }}
          HAPI_NETWORK_BASE_PASSWORD: ${{ secrets.DEV_HAPI_NETWORK_BASE_PASSWORD }}
          HAPI_NETWORK_WALLET_URL: ${{ secrets.DEV_HAPI_NETWORK_WALLET }}
          HAPI_HASURA_URL: ${{ secrets.DEV_HAPI_HASURA_URL }}
          HAPI_HASURA_ADMIN_SECRET: ${{ secrets.DEV_HAPI_HASURA_ADMIN_SECRET }}
          HAPI_RATE_HISTORY: ${{secrets.DEV_HAPI_RATE_HISTORY}}
          HAPI_EDEN_ELECTION_INTERVAL: 7889400
          HAPI_EDEN_HISTORIC_ELECTION: ${{secrets.DEV_HAPI_EDEN_HISTORIC_ELECTION}}
          HAPI_EDEN_CONTRACT: genesis.eden
          HAPI_DFUSE_API_KEY: 
          HAPI_DFUSE_API: jungle4.dfuse.eosnation.io
          HAPI_DFUSE_FIRST_BLOCK: ${{secrets.DEV_HAPI_DFUSE_FIRST_BLOCK}}
          # hasura
          HASURA_GRAPHQL_ENABLE_CONSOLE: true
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.DEV_HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.DEV_HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${{ secrets.DEV_HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}
          HASURA_GRAPHQL_ACTION_BASE_URL: ${{ secrets.DEV_HASURA_GRAPHQL_ACTION_BASE_URL }}

      - name: Deploy kubernetes files
        uses: steebchen/kubectl@v1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: eden-spending
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes
